var ctx = {
    "INITIAL_PARAMS": {
        "appPlatform": "web",
        "appVersion": "1.00.11",
        "origin": "",
        "email": "goodeggs@kodif.io",
        "requesterId": null,
        "customerId": "622358",
        "orderId": "835070"
    },
    "FLOW": "e3a0cd5b-4cdb-46dd-bfe5-8c2e65e8d841",
    "FLOW_VERSION": "df5df6dc-aa75-4396-87cf-b199b7e01663",
    "SESSION": {
        "key": "5a0fa33a-93cb-4efe-837f-56279e857f10"
    },
    "allOrders": [
        "Successful",
        200,
        {
            "all_jobs": [
                {
                    "job_seller_count": 1,
                    "job_status": 13,
                    "pd_or_appointment": 1,
                    "business_type": 1,
                    "merchant_name": "Roller Toaster Test",
                    "store_name_json": "{\"en\": \"Roller Toaster Test\"}",
                    "storefront_user_id": 297220,
                    "user_id": 297220,
                    "order_id": 622358,
                    "job_id": 835070,
                    "pickup_job_status": 2,
                    "delivery_job_status": 2,
                    "seller_id": 297220,
                    "creation_datetime": "2022-02-10T06:31:33.000Z",
                    "job_delivery_datetime": "February 10th 2022, 11:31 AM",
                    "job_delivery_datetime_utc": "2022-02-10T06:31:47.000Z",
                    "job_description": "",
                    "marketplace_user_id": 176005,
                    "product_id": 0,
                    "job_pickup_datetime": "February 10th 2022, 4:06 AM",
                    "job_address": "1600 Amphitheatre Pkwy, Mountain View, CA 94043, USA",
                    "payment_type": "CASH",
                    "customer_rating": null,
                    "is_custom_order": 0,
                    "order_currency_symbol": "PKR",
                    "refunded_amount": null,
                    "total_amount": 897,
                    "order_amount": 798,
                    "delivery_method": 2,
                    "job_pickup_address": "1600 Amphitheatre Pkwy, Mountain View, CA 94043, USA",
                    "job_pickup_phone": "+996770905425",
                    "job_pickup_name": "Elvira",
                    "merchant_is_deleted": 0,
                    "pickup_tracking_link": "",
                    "delivery_tracking_link": "",
                    "agent_id": 0,
                    "customer_id": 622358,
                    "customer_username": "Elvira",
                    "task_type": 0,
                    "transaction_id": "0",
                    "transaction_status": null,
                    "overall_transaction_status": null,
                    "vendor_is_deleted": 0,
                    "order_preparation_time": 0,
                    "preparation_completed": 0,
                    "is_scheduled": 0,
                    "product_details": [
                        "Crisparatha$#@4.00",
                        "Kebbabish$#@3.00"
                    ],
                    "product_names": "Crisparatha, Kebbabish",
                    "job_pickup_datetime_utc": "2022-02-09T23:06:01.000Z",
                    "payment_method": 8,
                    "can_change_status": 1,
                    "customer_is_deleted": 0
                },
                {
                    "job_seller_count": 1,
                    "job_status": 13,
                    "pd_or_appointment": 1,
                    "business_type": 1,
                    "merchant_name": "Just Wing It Test",
                    "store_name_json": "{\"en\": \"Just Wing It Test\"}",
                    "storefront_user_id": 297233,
                    "user_id": 297233,
                    "order_id": 622358,
                    "job_id": 835069,
                    "pickup_job_status": 2,
                    "delivery_job_status": 2,
                    "seller_id": 297233,
                    "creation_datetime": "2022-02-10T06:27:10.000Z",
                    "job_delivery_datetime": "February 10th 2022, 11:27 AM",
                    "job_delivery_datetime_utc": "2022-02-10T06:27:26.000Z",
                    "job_description": "",
                    "marketplace_user_id": 176005,
                    "product_id": 0,
                    "job_pickup_datetime": "February 10th 2022, 4:01 AM",
                    "job_address": "1600 Amphitheatre Pkwy, Mountain View, CA 94043, USA",
                    "payment_type": "CASH",
                    "customer_rating": null,
                    "is_custom_order": 0,
                    "order_currency_symbol": "PKR",
                    "refunded_amount": null,
                    "total_amount": 792,
                    "order_amount": 693,
                    "delivery_method": 2,
                    "job_pickup_address": "1600 Amphitheatre Pkwy, Mountain View, CA 94043, USA",
                    "job_pickup_phone": "+996770905425",
                    "job_pickup_name": "Elvira",
                    "merchant_is_deleted": 0,
                    "pickup_tracking_link": "",
                    "delivery_tracking_link": "",
                    "agent_id": 0,
                    "customer_id": 622358,
                    "customer_username": "Elvira",
                    "task_type": 0,
                    "transaction_id": "0",
                    "transaction_status": null,
                    "overall_transaction_status": null,
                    "vendor_is_deleted": 0,
                    "order_preparation_time": 0,
                    "preparation_completed": 0,
                    "is_scheduled": 0,
                    "product_details": [
                        "BBQ Honey (5pc)$#@3.00",
                        "Mango Habanero (5pc)$#@3.00",
                        "Sweet Thai Chilli (5pc)$#@1.00"
                    ],
                    "product_names": "BBQ Honey (5pc), Mango Habanero (5pc), Sweet Thai Chilli (5pc)",
                    "job_pickup_datetime_utc": "2022-02-09T23:01:38.000Z",
                    "payment_method": 8,
                    "can_change_status": 1,
                    "customer_is_deleted": 0
                },
                {
                    "job_seller_count": 1,
                    "job_status": 13,
                    "pd_or_appointment": 1,
                    "business_type": 1,
                    "merchant_name": "sindhi sweet",
                    "store_name_json": "{\"en\": \"sindhi sweet\"}",
                    "storefront_user_id": 297219,
                    "user_id": 297219,
                    "order_id": 622358,
                    "job_id": 835065,
                    "pickup_job_status": 2,
                    "delivery_job_status": 2,
                    "seller_id": 297219,
                    "creation_datetime": "2022-02-10T06:17:09.000Z",
                    "job_delivery_datetime": "February 10th 2022, 11:17 AM",
                    "job_delivery_datetime_utc": "2022-02-10T06:17:31.000Z",
                    "job_description": "",
                    "marketplace_user_id": 176005,
                    "product_id": 0,
                    "job_pickup_datetime": "February 10th 2022, 3:51 AM",
                    "job_address": "1600 Amphitheatre Pkwy, Mountain View, CA 94043, USA",
                    "payment_type": "CASH",
                    "customer_rating": null,
                    "is_custom_order": 0,
                    "order_currency_symbol": "PKR",
                    "refunded_amount": null,
                    "total_amount": 248,
                    "order_amount": 149,
                    "delivery_method": 2,
                    "job_pickup_address": "1600 Amphitheatre Pkwy, Mountain View, CA 94043, USA",
                    "job_pickup_phone": "+996770905425",
                    "job_pickup_name": "Elvira",
                    "merchant_is_deleted": 0,
                    "pickup_tracking_link": "",
                    "delivery_tracking_link": "",
                    "agent_id": 0,
                    "customer_id": 622358,
                    "customer_username": "Elvira",
                    "task_type": 0,
                    "transaction_id": "0",
                    "transaction_status": null,
                    "overall_transaction_status": null,
                    "vendor_is_deleted": 0,
                    "order_preparation_time": 0,
                    "preparation_completed": 0,
                    "is_scheduled": 0,
                    "product_details": [
                        "Chicken Biryani$#@1.00",
                        "Chicken Pulao$#@1.00"
                    ],
                    "product_names": "Chicken Biryani, Chicken Pulao",
                    "job_pickup_datetime_utc": "2022-02-09T22:51:37.000Z",
                    "payment_method": 8,
                    "can_change_status": 1,
                    "customer_is_deleted": 0
                },
                {
                    "job_seller_count": 1,
                    "job_status": 13,
                    "pd_or_appointment": 1,
                    "business_type": 1,
                    "merchant_name": "Roller Toaster Test",
                    "store_name_json": "{\"en\": \"Roller Toaster Test\"}",
                    "storefront_user_id": 297220,
                    "user_id": 297220,
                    "order_id": 622358,
                    "job_id": 835061,
                    "pickup_job_status": 2,
                    "delivery_job_status": 2,
                    "seller_id": 297220,
                    "creation_datetime": "2022-02-10T06:03:42.000Z",
                    "job_delivery_datetime": "February 10th 2022, 11:04 AM",
                    "job_delivery_datetime_utc": "2022-02-10T06:04:14.000Z",
                    "job_description": "",
                    "marketplace_user_id": 176005,
                    "product_id": 0,
                    "job_pickup_datetime": "February 10th 2022, 3:38 AM",
                    "job_address": "1600 Amphitheatre Pkwy, Mountain View, CA 94043, USA",
                    "payment_type": "CASH",
                    "customer_rating": null,
                    "is_custom_order": 0,
                    "order_currency_symbol": "PKR",
                    "refunded_amount": 203,
                    "total_amount": 948,
                    "order_amount": 1052,
                    "delivery_method": 2,
                    "job_pickup_address": "1600 Amphitheatre Pkwy, Mountain View, CA 94043, USA",
                    "job_pickup_phone": "+996770905425",
                    "job_pickup_name": "Elvira",
                    "merchant_is_deleted": 0,
                    "pickup_tracking_link": "",
                    "delivery_tracking_link": "",
                    "agent_id": 0,
                    "customer_id": 622358,
                    "customer_username": "Elvira",
                    "task_type": 0,
                    "transaction_id": "0",
                    "transaction_status": null,
                    "overall_transaction_status": null,
                    "vendor_is_deleted": 0,
                    "order_preparation_time": 0,
                    "preparation_completed": 0,
                    "is_scheduled": 0,
                    "product_details": [
                        "Crisparatha$#@4.00",
                        "Kebbabish$#@4.00"
                    ],
                    "product_names": "Crisparatha, Kebbabish",
                    "job_pickup_datetime_utc": "2022-02-09T22:38:10.000Z",
                    "payment_method": 8,
                    "can_change_status": 1,
                    "customer_is_deleted": 0
                },
                {
                    "job_seller_count": 1,
                    "job_status": 13,
                    "pd_or_appointment": 1,
                    "business_type": 1,
                    "merchant_name": "Overloaded Test",
                    "store_name_json": "{\"en\": \"Overloaded Test\"}",
                    "storefront_user_id": 297232,
                    "user_id": 297232,
                    "order_id": 622358,
                    "job_id": 835060,
                    "pickup_job_status": 2,
                    "delivery_job_status": 2,
                    "seller_id": 297232,
                    "creation_datetime": "2022-02-10T05:56:57.000Z",
                    "job_delivery_datetime": "February 10th 2022, 10:57 AM",
                    "job_delivery_datetime_utc": "2022-02-10T05:57:33.000Z",
                    "job_description": "",
                    "marketplace_user_id": 176005,
                    "product_id": 0,
                    "job_pickup_datetime": "February 10th 2022, 3:31 AM",
                    "job_address": "1600 Amphitheatre Pkwy, Mountain View, CA 94043, USA",
                    "payment_type": "CASH",
                    "customer_rating": null,
                    "is_custom_order": 0,
                    "order_currency_symbol": "PKR",
                    "refunded_amount": null,
                    "total_amount": 1211,
                    "order_amount": 1112,
                    "delivery_method": 2,
                    "job_pickup_address": "1600 Amphitheatre Pkwy, Mountain View, CA 94043, USA",
                    "job_pickup_phone": "+996770905425",
                    "job_pickup_name": "Elvira",
                    "merchant_is_deleted": 0,
                    "pickup_tracking_link": "",
                    "delivery_tracking_link": "",
                    "agent_id": 0,
                    "customer_id": 622358,
                    "customer_username": "Elvira",
                    "task_type": 0,
                    "transaction_id": "0",
                    "transaction_status": null,
                    "overall_transaction_status": null,
                    "vendor_is_deleted": 0,
                    "order_preparation_time": 0,
                    "preparation_completed": 0,
                    "is_scheduled": 0,
                    "product_details": [
                        "Fiery Fries$#@5.00",
                        "Tikka Blast Fries$#@3.00"
                    ],
                    "product_names": "Fiery Fries, Tikka Blast Fries",
                    "job_pickup_datetime_utc": "2022-02-09T22:31:25.000Z",
                    "payment_method": 8,
                    "can_change_status": 1,
                    "customer_is_deleted": 0
                }
            ],
            "count": 5
        }
    ],
    "customerDetail": [
        "You don't have permission to access this resource.",
        211,
        {}
    ],
    "selectedOrder": [
        "Successful",
        200,
        [
            {
                "business_type": 1,
                "created_by": 10,
                "order_id": 622358,
                "job_id": 835070,
                "job_type": 0,
                "job_time": "2022-02-10T04:06:01.000Z",
                "has_delivery": 1,
                "has_pickup": 1,
                "job_description": "",
                "coupon_discount": 0,
                "return_enabled": 0,
                "job_pickup_phone": "+996770905425",
                "job_pickup_address": "1600 Amphitheatre Pkwy, Mountain View, CA 94043, USA",
                "job_pickup_datetime": "02/10/2022 04:06 am",
                "checkout_template": null,
                "job_delivery_datetime": "02/10/2022 11:31 am",
                "job_delivery_datetime_utc": "2022-02-10T06:31:47.000Z",
                "pickup_delivery_relationship": null,
                "fleet_id": 0,
                "creation_datetime": "2022-02-10T06:31:33.000Z",
                "vertical": 0,
                "marketplace_user_id": 176005,
                "created_at": "2022-02-10T06:31:33.000Z",
                "prepration_datetime": "0000-00-00 00:00:00",
                "preparation_completed": 0,
                "agent_arrived": 0,
                "form_id": 0,
                "updated_at": "2022-02-10T06:31:46.000Z",
                "transaction_id": "0",
                "refunded_amount": null,
                "remaining_balance": 0,
                "tax": 0,
                "delivery_charge": 99,
                "total_amount": 897,
                "order_amount": 798,
                "payment_type": "CASH",
                "surge_amount": 0,
                "wallet_deduction": 0,
                "negative_wallet": 0,
                "small_basket_fee": 0,
                "is_job_rated": 0,
                "is_rating_deleted": 0,
                "customer_rating": 0,
                "customer_comment": "",
                "pd_or_appointment": 1,
                "user_id": 297220,
                "merchant_email": "gopal1@yopmail.com",
                "merchant_phone_number": "+919998988834",
                "additional_charges": 0,
                "additional_charge_label": null,
                "overall_transaction_status": null,
                "merchant_name": "Roller Toaster Test",
                "store_name_json": "{\"en\": \"Roller Toaster Test\"}",
                "merchant_is_deleted": 0,
                "merchant_id": 297220,
                "banner_image": "https://byte-bkt.s3.ap-south-1.amazonaws.com/task_images/6uyC1617270131611-CrispyChickenrollRecipebyFoodfusion5.jpg",
                "is_cancel_allowed": 1,
                "tip": 0,
                "delivery_method": 2,
                "is_custom_order": 0,
                "task_type": 0,
                "is_urgent_delivery": 0,
                "customer_id": 622358,
                "customer_username": "Elvira",
                "transaction_status": null,
                "job_pickup_latitude": "37.4219983",
                "job_pickup_longitude": "-122.084",
                "job_latitude": "37.4219983",
                "job_longitude": "-122.084",
                "merchant_latitude": "30.700051",
                "merchant_longitude": "76.8466658",
                "fugu_channel_id": "",
                "is_pickup_anywhere": null,
                "job_pickup_email": "elvira@mail.ru",
                "job_pickup_name": "Elvira",
                "order_sent_to_pandago": 0,
                "merchant_module": 0,
                "admin_setting_for_merchant": 0,
                "delivery_by_merchant": null,
                "job_status": 13,
                "cancel_order_admin": 1,
                "promo_code": null,
                "customer_is_deleted": 0,
                "hold_amount": 0,
                "tookan_scheduled_datetime": null,
                "tookan_active_when_job_created": 634796,
                "merchant_earning": 239.4,
                "commission_amount": 657.6,
                "commission_payout_status": "UNPAID",
                "customer_rating_by_merchant": 0,
                "customer_review_by_merchant": "",
                "order_preparation_time": 0,
                "is_scheduled": 0,
                "currency_code": "PKR",
                "currency_symbol": "PKR",
                "merchant_payment_methods": 1,
                "merchant_currency_id": null,
                "transaction_charges": 0,
                "debt_amount": 0,
                "order_currency_symbol": "PKR",
                "customer_phone": "+996770905425",
                "job_address": "1600 Amphitheatre Pkwy, Mountain View, CA 94043, USA",
                "customer_email": "elvira@mail.ru",
                "payment_method": 8,
                "isEditAllowed": 1,
                "payment_name": "Cash",
                "isEditedTask": 0,
                "user_taxes": [],
                "show_status": 1,
                "orderDetails": [
                    {
                        "customizations": [],
                        "product": {
                            "order_item_id": 2081292,
                            "job_id": 835070,
                            "product_id": 3436954,
                            "seller_id": 297220,
                            "cust_id": null,
                            "unit_price": 99,
                            "cost_price": null,
                            "quantity": 4,
                            "total_price": 396,
                            "customization_linking": "48443941364437566947",
                            "status": 1,
                            "created_at": "2022-02-10T06:31:33.000Z",
                            "updated_at": "2022-02-10T06:31:33.000Z",
                            "inventory_enabled": 0,
                            "task_start_time": null,
                            "task_end_time": null,
                            "task_start_time_local": null,
                            "task_end_time_local": null,
                            "unit_type": 1,
                            "unit_count": 1,
                            "unit": 1,
                            "agent_id": 0,
                            "enable_tookan_agent": 0,
                            "is_product_template_enabled": 0,
                            "template_cost": 0,
                            "template": [],
                            "product_name": "Crisparatha",
                            "name_json": "{\"en\": \"Crisparatha\"}",
                            "product_image": "https://byte-bkt.s3.ap-south-1.amazonaws.com/task_images/7iKC1612442116437-crispratha.jpg",
                            "catalogue_id": 603909,
                            "category_name": "Paratha Rolls",
                            "category_name_json": "{\"en\": \"Paratha Rolls\"}",
                            "surge_type": 0,
                            "surge_amount": 0,
                            "include_intervals": null,
                            "multiPrice": [
                                {
                                    "unit": 1,
                                    "price_type": 1,
                                    "price": 99
                                }
                            ],
                            "taxes": [],
                            "dropdownQuantity": [
                                {
                                    "key": 1,
                                    "value": 1
                                },
                                {
                                    "key": 2,
                                    "value": 2
                                },
                                {
                                    "key": 3,
                                    "value": 3
                                },
                                {
                                    "key": 4,
                                    "value": 4
                                }
                            ]
                        },
                        "job_id": 835070
                    },
                    {
                        "customizations": [
                            {
                                "order_item_id": 2081294,
                                "job_id": 835070,
                                "product_id": null,
                                "seller_id": 297220,
                                "cust_id": 1875211,
                                "unit_price": 30,
                                "cost_price": null,
                                "quantity": 3,
                                "total_price": 90,
                                "customization_linking": "74933744845913466456",
                                "status": 1,
                                "created_at": "2022-02-10T06:31:33.000Z",
                                "updated_at": "2022-02-10T06:31:33.000Z",
                                "inventory_enabled": 0,
                                "task_start_time": null,
                                "task_end_time": null,
                                "task_start_time_local": null,
                                "task_end_time_local": null,
                                "unit_type": 1,
                                "unit_count": 1,
                                "unit": 1,
                                "agent_id": 0,
                                "enable_tookan_agent": 0,
                                "is_product_template_enabled": 0,
                                "template_cost": 0,
                                "cust_name": "Cheese",
                                "name_json": "{\"en\": \"Cheese\"}"
                            }
                        ],
                        "product": {
                            "order_item_id": 2081293,
                            "job_id": 835070,
                            "product_id": 3436955,
                            "seller_id": 297220,
                            "cust_id": null,
                            "unit_price": 104,
                            "cost_price": null,
                            "quantity": 3,
                            "total_price": 312,
                            "customization_linking": "74933744845913466456",
                            "status": 1,
                            "created_at": "2022-02-10T06:31:33.000Z",
                            "updated_at": "2022-02-10T06:31:33.000Z",
                            "inventory_enabled": 0,
                            "task_start_time": null,
                            "task_end_time": null,
                            "task_start_time_local": null,
                            "task_end_time_local": null,
                            "unit_type": 1,
                            "unit_count": 1,
                            "unit": 1,
                            "agent_id": 0,
                            "enable_tookan_agent": 0,
                            "is_product_template_enabled": 0,
                            "template_cost": 0,
                            "template": [],
                            "product_name": "Kebbabish",
                            "name_json": "{\"en\": \"Kebbabish\"}",
                            "product_image": "https://byte-bkt.s3.ap-south-1.amazonaws.com/task_images/o0z11612442249750-BeefreshmikababparatharollRecipebyFoodfusion1.jpg",
                            "catalogue_id": 603909,
                            "category_name": "Paratha Rolls",
                            "category_name_json": "{\"en\": \"Paratha Rolls\"}",
                            "surge_type": 0,
                            "surge_amount": 0,
                            "include_intervals": null,
                            "multiPrice": [
                                {
                                    "unit": 1,
                                    "price_type": 1,
                                    "price": 104
                                }
                            ],
                            "taxes": [],
                            "dropdownQuantity": [
                                {
                                    "key": 1,
                                    "value": 1
                                },
                                {
                                    "key": 2,
                                    "value": 2
                                },
                                {
                                    "key": 3,
                                    "value": 3
                                }
                            ]
                        },
                        "job_id": 835070
                    }
                ],
                "cancel_allowed": 0,
                "updated_by": "Manager",
                "reason": null,
                "cancellation_reason": null,
                "tookan_job_hash": null,
                "agent_id": 0,
                "loyalty_points": {},
                "fields": {
                    "custom_field": []
                },
                "is_customer_rated": 0,
                "link_tasks": [],
                "link_task": {},
                "job_vertical": 0,
                "acknowledged_datetime": "2022-02-10T09:40:51.455Z",
                "barcode": "",
                "arrived_datetime": "2022-02-10T09:40:51.455Z",
                "completed_by_admin": 0,
                "completed_datetime": "2022-02-10T09:40:51.455Z",
                "customer_rating_by_driver": 0,
                "distance_spent": 0,
                "driver_comment": "",
                "tookan_pickup_job_id": 0,
                "tookan_delivery_job_id": 0,
                "delivery_system_job_id": null,
                "team_id": 0,
                "team_name": "",
                "total_distance_travelled": 0,
                "recurring_id": 0,
                "region_id": 0,
                "region_name": "",
                "remarks": "",
                "started_datetime": "2022-02-10T09:40:51.456Z",
                "tags": "",
                "task_history": [
                    {
                        "creation_datetime": "2022-02-10T06:31:33.000Z",
                        "job_id": 0,
                        "fleet_id": 0,
                        "fleet_name": "",
                        "type": "",
                        "latitude": 0,
                        "longitude": 0,
                        "description": ""
                    }
                ],
                "total_order_amount": 708,
                "promoList": [],
                "transactionList": [
                    "0"
                ],
                "products_rating_data": [],
                "questions_and_tags": [
                    {
                        "questions_and_tags": {
                            "food": [],
                            "delivery": []
                        }
                    }
                ],
                "delivery_rating": 0,
                "hippo_transaction_id": "835070_undefined_297220",
                "grouping_tags": [
                    "GT_297220"
                ],
                "static_map_url": "",
                "business_model_type": "HYPERLOCAL_PRODUCT"
            }
        ]
    ],
    "USER_INPUTS": {
        "issueType": "0",
        "selectedOrderItemsConfirm": "0",
        "items": [
            {
                "selectedOrderItems": [
                    "0"
                ],
                "dropdownQty": 1
            },
            {
                "selectedOrderItems": [
                    "1"
                ],
                "dropdownQty": 1
            }
        ]
    },
    "customerEmail": "elvira@mail.ru",
    "issueName": "Incomplete order",
    "selectedItemsText": "1 - Crisparatha; 1 - Kebbabish; ",
    "hasRefundBefore": "",
    "refundAmount": 203
}